### ISSUE TITLE
java.io.IOException: close failed: EPERM (Operation not permitted)  when we copy file from storage to our ntfs usb devices

### ISSUE THREAD

**Issue by caiyongnjupt** [tuxera/ntfs-3g#127]
Dear developer

We used the ntfs-3g code for our android system, but have some IO error when we copy file from storage to our ntfs usb devices

like

10-18 10:49:12.951  2200  8756 E r       : Error copying file
10-18 10:49:12.951  2200  8756 E r       : java.io.IOException: close failed: EPERM (Operation not permitted)
10-18 10:49:12.951  2200  8756 E r       :     at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:254)
10-18 10:49:12.951  2200  8756 E r       :     at java.io.FileOutputStream.close(FileOutputStream.java:431)
10-18 10:49:12.951  2200  8756 E r       :     at sun.nio.ch.FileChannelImpl.implCloseChannel(FileChannelImpl.java:164)
10-18 10:49:12.951  2200  8756 E r       :     at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:116)
10-18 10:49:12.951  2200  8756 E r       :     at com.meizu.media.gallery.cloud.r.d(SourceFile:18)
10-18 10:49:12.951  2200  8756 E r       :     at com.meizu.media.gallery.utils.FACopyUtils.lambda$copyFileToDestFolder$8(SourceFile:19)
10-18 10:49:12.951  2200  8756 E r       :     at com.meizu.media.gallery.utils.FACopyUtils.d(Unknown Source:0)
10-18 10:49:12.951  2200  8756 E r       :     at com.meizu.media.gallery.utils.f.run(Unknown Source:11)
10-18 10:49:12.951  2200  8756 E r       :     at com.meizu.media.common.utils.y$g.run(SourceFile:2)
10-18 10:49:12.951  2200  8756 E r       :     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-18 10:49:12.951  2200  8756 E r       :     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-18 10:49:12.951  2200  8756 E r       :     at java.lang.Thread.run(Thread.java:923)
10-18 10:49:12.951  2200  8756 E r       :     at com.meizu.media.common.utils.r$a.run(SourceFile:2)
10-18 10:49:12.951  2200  8756 E r       : Caused by: android.system.ErrnoException: close failed: EPERM (Operation not permitted)
10-18 10:49:12.951  2200  8756 E r       :     at libcore.io.Linux.close(Native Method)
10-18 10:49:12.951  2200  8756 E r       :     at libcore.io.ForwardingOs.close(ForwardingOs.java:88)
10-18 10:49:12.951  2200  8756 E r       :     at libcore.io.BlockGuardOs.close(BlockGuardOs.java:110)
10-18 10:49:12.951  2200  8756 E r       :     at libcore.io.ForwardingOs.close(ForwardingOs.java:88)
10-18 10:49:12.951  2200  8756 E r       :     at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:252)
10-18 10:49:12.951  2200  8756 E r       :     ... 12 more

Can you help me ?
thanks

**Comment by BOBA1985** [comment]
> Dear developer
> 
> We used the ntfs-3g code for our android system, but have some IO error when we copy file from storage to our ntfs usb devices
> 
> like
> 
> 10-18 10:49:12.951  2200  8756 E r       : Error copying file
> 10-18 10:49:12.951  2200  8756 E r       : java.io.IOException: close failed: EPERM (Operation not permitted)
> 10-18 10:49:12.951  2200  8756 E r       :     at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:254)
> 10-18 10:49:12.951  2200  8756 E r       :     at java.io.FileOutputStream.close(FileOutputStream.java:431)
> 10-18 10:49:12.951  2200  8756 E r       :     at sun.nio.ch.FileChannelImpl.implCloseChannel(FileChannelImpl.java:164)
> 10-18 10:49:12.951  2200  8756 E r       :     at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:116)
> 10-18 10:49:12.951  2200  8756 E r       :     at com.meizu.media.gallery.cloud.r.d(SourceFile:18)
> 10-18 10:49:12.951  2200  8756 E r       :     at com.meizu.media.gallery.utils.FACopyUtils.lambda$copyFileToDestFolder$8(SourceFile:19)
> 10-18 10:49:12.951  2200  8756 E r       :     at com.meizu.media.gallery.utils.FACopyUtils.d(Unknown Source:0)
> 10-18 10:49:12.951  2200  8756 E r       :     at com.meizu.media.gallery.utils.f.run(Unknown Source:11)
> 10-18 10:49:12.951  2200  8756 E r       :     at com.meizu.media.common.utils.y$g.run(SourceFile:2)
> 10-18 10:49:12.951  2200  8756 E r       :     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 10-18 10:49:12.951  2200  8756 E r       :     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 10-18 10:49:12.951  2200  8756 E r       :     at java.lang.Thread.run(Thread.java:923)
> 10-18 10:49:12.951  2200  8756 E r       :     at com.meizu.media.common.utils.r$a.run(SourceFile:2)
> 10-18 10:49:12.951  2200  8756 E r       : Caused by: android.system.ErrnoException: close failed: EPERM (Operation not permitted)
> 10-18 10:49:12.951  2200  8756 E r       :     at libcore.io.Linux.close(Native Method)
> 10-18 10:49:12.951  2200  8756 E r       :     at libcore.io.ForwardingOs.close(ForwardingOs.java:88)
> 10-18 10:49:12.951  2200  8756 E r       :     at libcore.io.BlockGuardOs.close(BlockGuardOs.java:110)
> 10-18 10:49:12.951  2200  8756 E r       :     at libcore.io.ForwardingOs.close(ForwardingOs.java:88)
> 10-18 10:49:12.951  2200  8756 E r       :     at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:252)
> 10-18 10:49:12.951  2200  8756 E r       :     ... 12 more
> 
> Can you help me ?
> thanks

**Comment by jpandre** [comment]
It would be quite a challenge to provide some ntfs-3g oriented help with no information about how ntfs-3g has been plugged into Java and Android.

On Posix, which ntfs-3g is expected to conform to, close() cannot return EPERM (https://pubs.opengroup.org/onlinepubs/9699919799/functions/close.html), but Android and the Java environment may have their say.
