### ISSUE TITLE
NTFS-3G doesn't make extended attributes discoverable, for backup

### ISSUE THREAD

**Issue by vmlemon** [tuxera/ntfs-3g#129]
Using NTFS-3G version:
```
tyson@DESKTOP-6HH5CK9:/mnt/e$ ntfs-3g -v
ntfs-3g: No device is specified.

ntfs-3g 2021.8.22 integrated FUSE 28 - Third Generation NTFS Driver
                Configuration type 7, XATTRS are on, POSIX ACLS are on

Copyright (C) 2005-2007 Yura Pakhuchiy
Copyright (C) 2006-2009 Szabolcs Szakacsits
Copyright (C) 2007-2021 Jean-Pierre Andre
Copyright (C) 2009-2020 Erik Larsson

Usage:    ntfs-3g [-o option[,...]] <device|image_file> <mount_point>

Options:  ro (read-only mount), windows_names, uid=, gid=,
          umask=, fmask=, dmask=, streams_interface=.
          Please see the details in the manual (type: man ntfs-3g).

Example: ntfs-3g /dev/sda1 /mnt/windows

Plugin path: /usr/lib/x86_64-linux-gnu/ntfs-3g

News, support and information:  https://github.com/tuxera/ntfs-3g/
```

Running on Ubuntu 22.04.3 LTS.

During the process of reporting https://github.com/restic/restic/issues/5111, I noticed that although it was possible to obtain extended attributes, for files that were copied from OS/2 HPFS volumes, under older versions of Windows NT, by manually running ```getfattr -n system.ntfs_ea```,  they were inaccessible, by running pax/tar, or Restic, and do not appear, if I attempt ```getfattr -d ```, as suggested in that issue report. I also noticed, that the ```xattr``` tools do not always reliably interact with them.

With that in mind, whilst I'm unsure if this is by design, or a bug, it would make backing up, and restoring files from NTFS volumes more reliable, and consistent, in terms of data integrity, if this metadata was always exposed via the xattr mechanisms.

**Comment by vmlemon** [comment]
I haven't tested this, yet - but, it sounds like it *might* be possible to specify a mapping file, containing the following, at mount time (``ntfs-3g -o xattrmapping=/root/ntfs-attrs.txt```), with a fairly recent version of NTFS-3G:

```
system.ntfs_attrib:user.ntfs_attrib
system.ntfs_times:user.ntfs_times
system.ntfs_attrib_be:user.ntfs_attrib_be
system.ntfs_reparse_data:user.ntfs_reparse_data
system.ntfs_acl:user.ntfs_acl
system.ntfs_dos_name:user.ntfs_dos_name
system.ntfs_times:user.ntfs_times 
system.ntfs_times_be:user.ntfs_times_be
system.ntfs_crtime:user.ntfs_crtime
system.ntfs_crtime_be:user.ntfs_crtime_be
system.ntfs_object_id:user.ntfs_object_id
system.ntfs_efsinfo:user.ntfs_efsinfo
system.ntfs_ea:user.ntfs_ea
```
Not ideal, but if it works, I'll report back...

**Comment by vmlemon** [comment]
Aha!

If I mount my disk image, with ```ntfs-3g -o ro -o xattrmapping=/home/tyson/ntfs-attrs.txt /dev/mapper/loop0p1 /tmp/1/``` (i.e. it will not work, with a relative path, to the ```ntfs-attrs.txt```, or "combined style" arguments, to ```-o``` (i.e. ``` -o ro xattrmapping,ntfs-attrs.txt```), it looks like their workaround kinda works, with the caveat of data encoding issues, in the attribute values:

```
root@DESKTOP-6HH5CK9:/home/tyson# xattr -l /tmp/1
user.ntfs_attrib:
0000   36 00 00 00                                        6...

Traceback (most recent call last):
  File "/usr/bin/xattr", line 33, in <module>
    sys.exit(load_entry_point('xattr==0.9.7', 'console_scripts', 'xattr')())
  File "/usr/lib/python3/dist-packages/xattr/tool.py", line 196, in main
    attr_value = attr_value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 2: invalid start byte
root@DESKTOP-6HH5CK9:/home/tyson# getfattr -d /tmp/1/
getfattr: Removing leading '/' from absolute path names
# file: tmp/1/
user.ntfs_acl=0sAQAEkIwAAACcAAAAAAAAABQAAAACAHgABQAAAAAEGACYAR8AAQIAAAAAAAUgAAAAIAIAAAAEGACIABIAAQIAAAAAAAUgAAAAIAIAAAAEFACIABIAAQEAAAAAAAEAAAAAAAQYAL8BHwABAgAAAAAABSAAAAAgAgAAAAQUAL8BHwABAQAAAAAABRIAAAABAgAAAAAABSAAAAAgAgAAAQIAAAAAAAUgAAAAIAIAAA==
user.ntfs_attrib=0sNgAAAA==
user.ntfs_attrib_be=0sAAAANg==
user.ntfs_crtime=0sFlitXjbTygE=
user.ntfs_crtime_be=0sAcrTNl6tWBY=
/tmp/1/: user.ntfs_dos_name: Operation not permitted
/tmp/1/: user.ntfs_ea: No such attribute
/tmp/1/: user.ntfs_object_id: No such attribute
user.ntfs_times=0sFlitXjbTygGKi2QmQtPKAZiyayZC08oBiotkJkLTygE=
user.ntfs_times_be=0sAcrTNl6tWBYBytNCJmSLigHK00Ima7KYAcrTQiZki4o=
```

Obviously, it doesn't expose them, via the system.* attributes, in a nice way, but I guess it's better than nothing, for trying to back up their contents?

**Comment by vmlemon** [comment]
Looks like Restic will at least try to access the mapped attributes, and will complain about ones that fail through:

```
root@DESKTOP-6HH5CK9:/home/tyson# ~/restic_0.17.1_linux_amd64 -v --insecure-no-password -r /mnt/e/Archive3 backup /tmp/1/
open repository
repository f8b018ac opened (version 2, compression level auto)
found 3 old cache directories in /root/.cache/restic, run `restic cache --cleanup` to remove them
using parent snapshot 1f82f9fa
load index files
[0:09] 100.00%  126 / 126 index files loaded
start scan on [/tmp/1/]
start backup on [/tmp/1/]
scan finished in 12.112s: 16 files, 7.249 KiB
can not obtain extended attribute user.ntfs_dos_name for /tmp/1:

Files:          15 new,     1 changed,     0 unmodified
Dirs:            1 new,     2 changed,     0 unmodified
Data Blobs:     14 new
Tree Blobs:      4 new
Added to the repository: 27.771 KiB (7.577 KiB stored)

processed 16 files, 7.249 KiB in 0:13
snapshot 5cced57c saved
```

And, if I mount my repository, it looks like it's preserved the mapped attributes, and their contents:

```
root@DESKTOP-6HH5CK9:/mnt/e# getfattr -d /tmp/1/snapshots/latest/tmp/1/
getfattr: Removing leading '/' from absolute path names
# file: tmp/1/snapshots/latest/tmp/1/
user.ntfs_acl=0sAQAEkIwAAACcAAAAAAAAABQAAAACAHgABQAAAAAEGACYAR8AAQIAAAAAAAUgAAAAIAIAAAAEGACIABIAAQIAAAAAAAUgAAAAIAIAAAAEFACIABIAAQEAAAAAAAEAAAAAAAQYAL8BHwABAgAAAAAABSAAAAAgAgAAAAQUAL8BHwABAQAAAAAABRIAAAABAgAAAAAABSAAAAAgAgAAAQIAAAAAAAUgAAAAIAIAAA==
user.ntfs_attrib=0sNgAAAA==
user.ntfs_attrib_be=0sAAAANg==
user.ntfs_crtime=0sFlitXjbTygE=
user.ntfs_crtime_be=0sAcrTNl6tWBY=
/tmp/1/snapshots/latest/tmp/1/: user.ntfs_ea: No such attribute
/tmp/1/snapshots/latest/tmp/1/: user.ntfs_object_id: No such attribute
user.ntfs_times=0sFlitXjbTygGKi2QmQtPKAZiyayZC08oBiotkJkLTygE=
user.ntfs_times_be=0sAcrTNl6tWBYBytNCJmSLigHK00Ima7KYAcrTQiZki4o=
```
Whilst it'd be nice, if the NTFS-3G folks would fix their code, I guess this could be considered a "documentation bug", in terms of bear traps, that folks will be unaware of, especially considering that NTFS EAs are becoming more prevalent, with the rise of Windows Subsystem for Linux?

**Comment by jpandre** [comment]
On Linux, the extended attributes sit in several name spaces : user, system, security, ... and the permissions to read or update them depend on the name space. Also "getfattr -d" only shows the attributes in the user name space.

For example, on ext3 as a user :
```
[linux@optiplex ext3]$ echo foo > bar
[linux@optiplex ext3]$ setfattr -n system.ntfs_ea -v foo bar
setfattr: bar: Operation not supported
[linux@optiplex ext3]$ setfattr -n user.color -v green bar
[linux@optiplex ext3]$ getfattr -d bar
# file: bar
user.color="green"
```
Now, as root, set a Posix ACL (which is setting system.posix_acl_access) to enable executing by root :
```
root@optiplex ext3]# setfacl -m u:root:5 bar
[root@optiplex ext3]# getfacl bar
# file: bar
# owner: linux
# group: linux
user::rw-
user:root:r-x
group::r--
mask::r-x
other::r--

[root@optiplex ext3]# getfattr -n system.posix_acl_access -e hex bar
# file: bar
system.posix_acl_access=0x0200000001000600ffffffff020005000000000004000400ffffffff10000500ffffffff20000400ffffffff

[root@optiplex ext3]# getfattr -d bar
# file: bar
user.color="green"

```
The extended attribute is present in the system name space, but is not shown by "getfattr -d", so ntfs-3g abides by Linux rules.

**Comment by vmlemon** [comment]
Thanks for the info. 

I guess that the only ways of retrieving this metadata, from up the VFS layer, are either explicitly requesting each xattr (I assume this is how SELinux attributes are also supposed to be handled), by name, the mount-time mapping technique, or maintaining a local patch, to expose them, in some other namespace, then?

In any case, I suspect that the Linux kernel devs won't change the behaviour, to avoid breaking things, so I'm unsure how far, down the rabbit hole, to persue this. 

In the meantime, the mapping file method gets me most of the way there, for doing one-off backups, of some older NTFS volumes, that contain files migrated from OS/2 HPFS ones.

**Comment by kgermanov** [comment]
@vmlemon  Using xattrmapping is easy:

```
# cat ~/xattrMapping
system.ntfs_acl:user.ntfs_acl
system.ntfs_attrib:user.ntfs_attrib
system.ntfs_times:user.ntfs_times

# mount -t ntfs-3g -o ro,loop,big_writes,xattrmapping=$(realpath ~/xattrMapping) ntfs.img /tmp/testmount/

# getfattr -dP -e hex /tmp/testmount/Windows
getfattr: Removing leading '/' from absolute path names
  # file: tmp/testmount/Windows
user.ntfs_acl=0x01001490080100002801000000000000140000000200f4000900000000002800ff011f00010600000000000550000000b589fb381984c2cb5c6c236d5700776ec0026487000a280000000010010600000000000550000000b589fb381984c2cb5c6c236d5700776ec002648700001400bf011300010100000000000512000000000b14000000001001010000000000051200000000001800bf01130001020000000000052000000020020000000b1800000000100102000000000005200000002002000000001800a900120001020000000000052000000021020000000b1800000000a001020000000000052000000021020000000b140000000010010100000000000300000000010600000000000550000000b589fb381984c2cb5c6c236d5700776ec0026487010600000000000550000000b589fb381984c2cb5c6c236d5700776ec0026487
user.ntfs_attrib=0x10000000
user.ntfs_times=0x7cc7b0fd3104ca01109fbc8b43d9da01109fbc8b43d9da01109fbc8b43d9da01
```
